import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Button } from "../../../../../@/components/ui/button";
import { CardContent, Card } from "../../../../../@/components/ui/card";
import { CheckIcon, XIcon } from "../../../../../public/itemIcons/itemIcons";
import { ClaimModal } from "../../../../components/modal/ClaimModal";
export const LoggedClaimDetails = ({ isOpen, onClose, item, onAccept, onReject }) => {
    const [isClaimModalOpen, setIsClaimModalOpen] = useState(false);
    const modalClass = isOpen ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none';
    const defaultImage = "/public/placeholderImg.svg"; // replace with your default image path
    const stopPropagation = (event) => {
        event.stopPropagation();
    };
    if (isClaimModalOpen) {
        return _jsx(ClaimModal, { isOpen: isClaimModalOpen, onClose: () => setIsClaimModalOpen(false), itemId: item._id });
    }
    return (_jsxs("div", { className: `fixed inset-0 flex items-center justify-center z-50 transition-opacity duration-200 ease-in ${modalClass}`, onClick: onClose, children: [_jsx("div", { className: "absolute  inset-0 bg-black opacity-50" }), _jsx("main", { className: "w-11/12 sm:w-full max-w-screen-sm mx-auto p-4 md:p-4 md:py-6 lg:py-3 rounded-lg z-10 max-h-[90vh] overflow-auto", onClick: stopPropagation, children: _jsx(Card, { className: "p-2 rounded-3xl", children: _jsxs(CardContent, { children: [_jsx("h1", { className: "text-3xl pl-2 py-4 font-bold tracking-tighter sm:text-4xl md:text-4xl", children: "Claim Details" }), _jsx("p", { className: "text-gray-500 pl-2 text-xl mb-3 dark:text-gray-400 max-w-[650px]", children: "Details of claim report sent by the user" }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsx("div", { children: _jsx("img", { src: item.image || defaultImage, alt: item.title, className: "w-full h-auto object-cover rounded-2xl" }) }), _jsxs("div", { className: "pl-5", children: [_jsx("p", { className: "text-3xl mb-1", children: item.title }), _jsx("h3", { children: "How you lost it?" }), _jsxs("p", { className: "text-2xl pl-1 text-gray-500 mb-8", children: [" ", item.description] }), _jsxs("p", { className: "text-xl text-gray-500 pl-1  mb-2", children: ["Reported Date: ", item.reportedDate] }), _jsxs("p", { className: "text-xl text-gray-500 pl-1 mb-2", children: ["Reported By: ", item.reportedBy] }), _jsxs("p", { className: "text-xl text-gray-500 pl-1 mb-2", children: ["Location: ", item.location] }), _jsx("p", { children: "Additional Details: " })] })] }), _jsxs("div", { className: "flex justify-between mt-4", children: [_jsx(Button, { className: "text-2xl pt-8", onClick: onClose, children: "Close" }), _jsxs("div", { children: [_jsxs(Button, { onClick: () => onAccept(item), className: "h-14 mr-3 text-xl cursor-pointer overflow-visible rounded border-none bg-[#262626] px-7 text-center text-[#e5e5e5] shadow-md transition-colors duration-150 ease-out hover:bg-[#333333] active:bg-[#444444] active:text-[#ffffff]", size: "sm", variant: "outline", children: [_jsx(CheckIcon, { className: "w-9 h-9" }), _jsx("p", { className: "text-lg ", children: "Accept" })] }), _jsxs(Button, { onClick: () => onReject(item), className: "h-14 text-xl cursor-pointer overflow-visible rounded border-none bg-[#262626] px-7 text-center text-[#e5e5e5] shadow-md transition-colors duration-150 ease-out hover:bg-[#333333] active:bg-[#444444] active:text-[#ffffff]", variant: "outline", children: [_jsx(XIcon, { className: "w-9 h-9" }), _jsx("p", { className: "text-lg", children: "Deny" })] })] })] })] }) }) }, "1")] }));
};
